DerpXmlWrite_New()
//DerpXmlWrite_Config('', '')
DerpXmlWrite_OpenTag('a')
/*DerpXmlWrite_OpenTag('b')
DerpXmlWrite_Text('derp')
DerpXmlWrite_CloseTag()*/
DerpXmlWrite_LeafElement('b', 'derp')
DerpXmlWrite_CloseTag()
show_debug_message('')
show_debug_message(DerpXmlWrite_GetString())
DerpXmlWrite_Finish()
