show_debug_message('')
DerpXmlWrite_New()
DerpXmlWrite_OpenTag('a')
DerpXmlWrite_LeafElement('b', 'derp')
DerpXmlWrite_OpenTag('c')
DerpXmlWrite_CloseTag()
DerpXmlWrite_LeafElement('d', '')
DerpXmlWrite_CloseTag()
show_debug_message(DerpXmlWrite_GetString())
DerpXmlWrite_Finish()
